name: MaySevenDesign
favicon: null
layout_spectrum: 0.90749
typography_spectrum: 0.4786206712014973
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17201d'
    - '#e8dcda'
    - '#bec2c3'
    - '#8d9f9f'
    - '#687467'
  brandStrength: 0.8125
  lightness: 0.7418870620895177
  saturation: 0.6353166177868843
  rhythmicContrast: 0.31678330688737333
purpose: []
